target 'Rating Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rating Demo
  pod 'FloatRatingView', :path => '../'
end
